pipeline { 
    agent any  
    tools { 
        maven 'MAVEN' 
    }
    stages { 
        stage('Build') { 
            steps { 
               echo 'This is my first minimal pipeline.' 
            }
        }
    }
}